### ISSUE TITLE
LuceneIndexer not allows to override IsReadable method

### ISSUE THREAD

**Issue by bielu** [Shazwazza/Examine#112]
As method internal bool IsReadable(out Exception ex) is internal I am not able to override method even if my index is not using the filesystem to store my indexes. I created custom Elastic search provider on the base of Examine but I am not able to say my index is readable for Umbraco.
I would ask to change the method in follow to:
https://stackoverflow.com/questions/2564425/inheritence-in-c-sharp-question-is-overriding-internal-methods-possible
to be:
public virtual bool 
Should I create for a pull request?
Many thanks

**Comment by Shazwazza** [comment]
Hi, sorry it's taken so long to get back to you, been too busy recently.

The version you are trying to build an elastic search provider for may prove to be difficult to integrate properly with Umbraco and Umbraco back office in v7. The main problem is that Umbraco is too strongly tied to the `LuceneIndex` base class, but i assume that might be why you are inheriting from it? 

Happy to accept a PR so you can override it, would be interested to see how your implementation goes.

Would love to see an elastic search implementation and in Umbraco v8, creating an Elastic Search provider will be much nicer and it will be able to integrate nicely within Umbraco since it's no longer tied to `LuceneIndexer`. I've made most of an Azure Search provider already in the Examine 1.0 (which is used in Umbraco v8), hoping to release it in the coming months.

**Comment by bielu** [comment]
HI @Shazwazza, Thanks for the answer.
I am already working on PR to Examine but change will require few changes in Umbraco, I will prepare that changes in PR for Umbraco soon. It is really hard to cooperate with LuceneIndexer :).

**Comment by Shazwazza** [comment]
Yeah, i had a branch for both examine and umbraco to make a lot of this work but that's been discontinued because we've made that all work in v8. v7 will probably not get many feature updates unless they are small things.

**Comment by bielu** [comment]
@Shazwazza here I have quick question about that part of Examine Extension:
`public static bool IsHealthy(this LuceneIndexer indexer, out Exception ex)
        {
            try
            {
                using (indexer.GetIndexWriter().GetReader())
                {
                    ex = null;
                    return true;
                }
            }
            catch (Exception e)
            {
                ex = e;
                return false;
            }
        }`
what you didn't done that in just that way:
`public static bool IsHealthy(this IIndexer indexer, out Exception e)
        {
            var readable = indexer.IsReadable(out ex);
            e = ex;
            return readable;
        }`
? 
If you guide me here would be great :), I am asking because from my perspective is doing exactly what should.

**Comment by Shazwazza** [comment]
From memory i think it's because IsReadable doesn't actually open the index and do all of the checks that actually getting a reader does. It was a while ago that I did that so I'd have to go check in the lucene code.

**Comment by bielu** [comment]
@Shazwazza I give up on v7, but I have started working on v8 version, could you provide me a small tip on how to switch providers for examine?
I am looking on your code here:
https://github.com/Shazwazza/Examine/tree/azure-search-1.0/src/Examine.AzureSearch
but I think I missing information about how to switch out indexes to use different providers.
