### ISSUE TITLE
Random sort

### ISSUE THREAD

**Issue by RaminMT** [Shazwazza/Examine#124]
Hi
Is there a way to get random ordered result with examine? If yes how? If no what do you suggest for that?

**Comment by Shazwazza** [comment]
I'm sure there's probably some way but i've never investigated that. You could ask if anyone has done this on the umbraco forum our.umbraco.org or you could dive into the source code and have a look at the https://github.com/Shazwazza/Examine/blob/master/src/Examine/LuceneEngine/LuceneSearchResults.cs which is where the searching/collecting happens. Since there's no way to actively swap out the collector logic in there you can't just 'inject' your own collector. However, one way or another it would probably be possible to override some classes and eventually be able to use your own LuceneSearchResult implementation. 

The current codebase is for 1.x version, previous 0.9.x versions are a bit different, it still uses collectors.

If you want to pursue this, I'd recommend cloning the repo and uses the unit tests or web test project to start playing around with the LuceneSearchResults and search online for random ordered results with Lucene. If you can solve it then let me know and can figure out a way for you to swap out the collector in Examine.
