### ISSUE TITLE
OrderBy not working for string fields

### ISSUE THREAD

**Issue by NikRimington** [Shazwazza/Examine#126]
Hi Shannon,

I'm having an issue sorting Examine results based on a string field. This is occurring in an Umbraco v8 site and I've reproduced the issue with the Umbraco v8 starter kit.

When attempting to sort the ExternalIndex based on a string field value sorting doesn't appear to be applied.

Adding this code at the top of the Blog.cshtml file is how I'm testing the OrderBy method:

```
ISearcher searcher;
IIndex index;
if(ExamineManager.Instance.TryGetIndex("ExternalIndex", out index))
{
   searcher = index.GetSearcher();
   var query = searcher.CreateQuery().NodeTypeAlias("blogPost").OrderBy(new Examine.Search.SortableField("nodeName", Examine.Search.SortType.String));
   var res = query.Execute();
   var t = res.Select(r => new { Id = r.Id, Name = r.Values["nodeName"] }).ToList();
 }
```

![image](https://user-images.githubusercontent.com/13313745/60168400-abb79a00-97fc-11e9-93cf-e35e5d733002.png)

As you can see the results are not sorted by their name as I would have expected. This has also been tested with other string fields and the same behaviour is happening.

**Comment by rizman** [comment]
I have a similar problem (also under Umbraco V8) for sorting Date fields. Lookings at the fields returned by the index in the Umbraco Backoffice, I see that Dates are returned by the index in the format dd/mm/yyyy hh:mm:ss instead of yyyy/mm/dd hh:mm:ss. If fields are sorted as strings by defaults, that would explain why my date sorting is off.

**Comment by Shazwazza** [comment]
There's 2 different issues here but lets try to figure them out...

Firstly you need to understand:

In v7 and Examine 0.9, for fields to be sortable you had to opt-in for them to be sortable which meant adding the sort flag to the Examine config.

In v8 and Examine 1.0, it is a similar story - by default text based fields do not have sorting enabled on them because this takes up double the space. 

Some examples in tests:

* https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L766
* https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L809
* https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L854

In Examine 1.0, each field is defined by a named definition, you can see in the last test above that a text based field to be sortable would need to be of type "fulltextsortable" (which is built-in), else it could be of a custom named type that you could define that is also sortable.  So in Umbraco 8, you would need to modify the field definition types during startup, in v7, you would need to add this to config. 

*Side note - Examine 1.0 is far more flexible and than previous versions because in previous versions, in order to define a field type in config meant you had to define __all__ of the fields you wanted indexed because as soon as you added one field to config, it meant you were in opt-in mode. Examine 1.0 will just index all data that is passed to it and you can easily on startup add a field definition for a field name.*

I realize this all needs to be documented, i will find the time one day for Examine but the Umbraco implementation of Examine will need to be documented on Our which is slowly in the works by Umbraco HQ. 

To add/modify a field definition on startup in Umbraco you can refer to these comments (and below) https://github.com/umbraco/Umbraco-CMS/issues/3535#issuecomment-446866319 ... the code isn't exactly correct because these examples were made during 8.0 development so things like IComponents, etc... are slightly different but that should get you started to be able to change your field `nodeName` to be "fulltextsortable"

@rizman as for yours - there's an example above in the tests on sorting by date. I'm unsure what date you are sorting on or what the syntax you are using is, you'l need to provide more details please.

**Comment by rizman** [comment]
@Shazwazza Thanks for your answer. I checked the test code on sorting by date. It basically is, what I'm doing in my code. I just added the SortType.Double Parameter. However, sorting is still not correct. 

Remember, this is in Umbraco 8.
I have a Document Type "Event" with a property "EventStartDate" and "EventEndDate". I would like to have Examine return results sorted by EventStartDate.

Basically, here is my code I use:
```
_searcher = _searchIndex.GetSearcher();
var results = _searcher.CreateQuery().Field("__NodeTypeAlias", "event").OrderBy(new SortableField("eventStartDate", SortType.Double)).Execute().ToArray();
```
My page template displays the items in the order provided by results. As you can see from the screenshot, items are not sorted correctly (I'm from Europe, so dates are in the format dd/MM/yyyy):
so we have: 30 June, 26 april, 30 June, 1 July...
![image](https://user-images.githubusercontent.com/745585/60645657-8ac4f980-9e39-11e9-9328-c5d95975f2c4.png)
Also, I noticed that using OrderByDescending does not change the results.

Checking the index in Umbraco Back Office using the Examine Management tab, I see that dates seem to be returned in American format. Maybe that's part of my problem??

![image](https://user-images.githubusercontent.com/745585/60645831-1b9bd500-9e3a-11e9-824b-efb8a56b8417.png)

The server (a Virtual Machine running Windows Server 2016 and SQL Express) is setup to display dates in the format dd/MM/yyyy (in case that matters)

Later, I want to achieve paging on my event listing page, but that first means the results need to be sorted correctly by Examine/Lucene.

Currently, I could handle sorting and paging in-memory, but what if over time, I have thousands of events on my DB? 

I will try adding a custom field "_sort_eventStartDate" to the index using your provided code, see if the problem comes from my custom date field?? Maybe Lucene doesn't know it's a date field and indexes it as a text field? (Umbraco's ModelBuilder correctly handles it as DateTime)

**Comment by Shazwazza** [comment]
@rizman it's because this field is not being indexed as a Date - Examine doesn't automatically know the types of data it's being given especially when there's custom user properties involved. This is the same as when using v7. 

So like above, during startup, you are going to have to tell the indexes what field type to use for your custom fields. If you want EventStartDate and EventEndDate to be indexed as dates then you need to tell it that these are dates. This is the link i mentioned above https://github.com/umbraco/Umbraco-CMS/issues/3535#issuecomment-446866319 and this is the test for sorting on dates where you can see what the field definition name for a date field should be https://github.com/Shazwazza/Examine/blob/master/src/Examine.Test/Search/FluentApiTests.cs#L809 (i.e. "date")

You're seeing the dates indexed as mm/dd/yyyy simply because that is the exact string that is being sent to the Examine to be indexed and right now it thinks it's a string, so it just indexes what it's given.

**Comment by rizman** [comment]
@Shazwazza Thanks for your quick response. It's what I was thinking in the end (see my last paragraph from above). I will change the index based on your code from your above mentioned issue

**Comment by Shazwazza** [comment]
@rizman sure, but you don't want to add any custom _sort_ fields ... just change the field definition to "date" and it will automatically be sortable. You'll need to rebuild your indexes too.

**Comment by rizman** [comment]
@Shazwazza I'll keep the issued updated once I have figured out the code in case someone else comes across this issue. Indeed it looks like there where some changes to the Component system in the released version form Umbraco compared to your provided code. I'll have to dig into it

**Comment by rizman** [comment]
So here is the modified code for the FieldDefinitions using Umbraco v8.

The Component system changed to implementing interfaces instead of inheriting from base classes as it seems to have been the case on @Shazwazza code example in the issue #3535

```
 public class ExamineComposer : IComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<ExamineComponent>();
        }
    }
```
```
 public class ExamineComponent : IComponent
    {
        public void Initialize(IExamineManager examineManager)
        {
            CustomizeIndexFields(examineManager);
        }

        private void CustomizeIndexFields(IExamineManager examineManager)
        {
            //This will update ALL indexes that are Lucene based, if you only want to update
            // a single index, then get the index with examineManager.TryGetIndex

            foreach (var umbIndex in examineManager.Indexes.OfType<LuceneIndex>())
            {
                umbIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("eventStartDate", "date"));
                umbIndex.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition("eventEndDate", "date"));
              
            }
        }

        public void Initialize()
        {
            Initialize(ExamineManager.Instance);
        }

        public void Terminate()
        {
        }
    }
```

Now, sorting on my dates does work correctly as the field is correctly populated in the index. 
![image](https://user-images.githubusercontent.com/745585/60652948-5eb17480-9e49-11e9-9d1a-e6048d0b8fe0.png)

**Comment by Shazwazza** [comment]
Nice! (_only note is that you'll prob want to user IUserComposer, this is documented https://our.umbraco.com/documentation/Implementation/Composing/_)

**Comment by rizman** [comment]
Indeed, you are correct. That is the recommended way. I modified my comment accordingly

**Comment by NikRimington** [comment]
Sorry for not coming back on this, thank you for your help with it @Shazwazza , adding the field explicitly during start up did allow it to be sorted.

Slight side tangent, is it possible to exclude document types from the external index? I tried to do it by attempting to modify the exclusion list, however it turns out it's read only at the point I was trying to access it.

**Comment by Shazwazza** [comment]
Thanks, will close this issue.

@NikRimington not sure why you want to exclude doc types from the index? Best practices are to have the least amount of indexes possible since there is overhead in maintaining more. So you should allow all data to go into an index and then just make sure your searching is configured to ignore certain things.
