### ISSUE TITLE
Push into Search methods into BaseSearchProvider or create a Interface and use it

### ISSUE THREAD

**Issue by ThomasSkyldahl** [Shazwazza/Examine#14]
Hi I am trying to integrate Elasticsearch into umbraco using Examine but I hit a roadblock as there are a few places in umbraco where the SearchProvider is cast to the specific LuceneSearcher to use a few extra Search methods implemented on the Specific searcher.

Would it be possible to create two abstract methods
BaseLuceneSearcher: ISearchResults  Search(ISearchCriteria searchParams, int maxResults)
LuceneSearcher: ISearchResults Search(string searchText, bool useWildcards, string indexType)

in the BaseSearchProvider, or create a Inferface for the methods that can be implemented by other providers. 

this would make it possible to avoid the casts in Umbraco that makes it difficult to implement SearchProviders based on other engines than Lucene.net?

Next up would be to refactor the usage of UmbracoContentIndexer in Umbraco as it its also tied to Lucene.net but that's another story. :-)

**Comment by Shazwazza** [comment]
I'm assuming you are attempting to do this by replacing the Examine providers with your own providers?

In which case the UmbracoContentIndexer can remain as-is since it's a specific implementation for Lucene.Net. If you wanted to replace the default index/search providers you'd just have to code up all of the requirements - this will include binding to all of the required core events to ensure your custom indexes stay up-to-date with the data. You would essentially need to copy all logic from Umbraco.Web.Search.ExamineEvents.

I realize the the casting to various types like: LuceneSearcher, UmbracoContentIndexer, etc...  in the Umbraco core is not ideal but these castings have been there to maintain backwards compatibility and the Examine library needs to respect the breaking change policy of Umbraco.

We can definitely move this in the right direction to hopefully make this possible without breaking stuff (it might not be pretty but should work). I can create this method in BaseSearchProvider which maintains compatibility since it doesn't force an override:

        public virtual ISearchResults Search(ISearchCriteria searchParams, int maxResults)
        {
            //returns base method with default maxResults
            return Search(searchParams);
        }

The 2nd method is a bit more tricky because there is no default to fallback to, so we'll have to implement this on BaseSearchProvider like:

        /// <summary>
        /// A simple search mechanism to search all fields based on an index type.
        /// </summary>
        /// <param name="searchText"></param>
        /// <param name="useWildcards"></param>
        /// <param name="indexType">By default this doesn't have any affect, it is up to inheritors to make this do something</param>
        /// <returns></returns>
        public virtual ISearchResults Search(string searchText, bool useWildcards, string indexType)
        {
            return Search(searchText, useWildcards);
        }

... again, not pretty but it will need to do for now.

More than happy to assist with this effort so back office search can be properly abstracted via Examine abstractions. Strangely I've been thinking about this last week! We'll of course need to update the Umbraco core too to remove the castings to the specific classes.

I've also created this for v8 so we don't forget http://issues.umbraco.org/issue/U4-6484 and v8 will be based on Examine v2.

**Comment by ThomasSkyldahl** [comment]
Yep Im trying to crate my own implementations but replacing the internal indexer and searcher is a problem as the EntityController.ExamineSearch is casting the Searcher to a BaseLuceneSearcher

Hmm! how fare out is v8 and Examine v2 It could be that I should base it around that instead, I just think it could be cool to bring in Elasticsearch for distributed umbraco deployments, where the current Lucene implementation kan be kind of annoying :-)

**Comment by Shazwazza** [comment]
Examine v2 is out in beta, you can get it from nuget, but it's not compatible with Umbraco v7. Umbraco v8 won't be out until probably late in the year and there's plenty of breaking changes which you can find on our.umbraco.org.

Yup i agree having the search/indexing abstracted correctly would be great. Umb distributed deployments even with Lucene will become much easier in 7.3.0 BTW with some new stuff we've been working on, but of course it would still be cool to have search/indexing abstracted so people can plug whatever they want in. 

I think pursuing this on v7 is a good idea and it is possible, just need to tweak a couple of things which hopefully will make this more possible. However, regardless of the abstractions, any custom indexers will need to bind to Umbraco events manually and keep the index up to date manually.

I'll implement these methods now and we already have this task for 7.2.5 so they can make it into that release: http://issues.umbraco.org/issue/U4-6474 and I'll update the task to remove the casts.

**Comment by ThomasSkyldahl** [comment]
Sounds Great! 

Right now Im just inheriting from UmbracoContentIndexer as it contains all the logic for coverting umbraco documents to the index types, but that will  have to go away later.

I overide the AddDocument method and use that for the indexing part  lets just call it a 'quick hack' :-)

But my first task is to create the ISearchCriteria implementation, and I can create that part with the current indexer after that I can create the real Indexer and refactor the small parts in the ISearchCriteria that needs tuning afterwards.

After that I will add features like aggregations and such.

**Comment by Shazwazza** [comment]
Cool, keep me posted about progress and any updates that you might need to umb or examine core and I'll do my best so long as we don't have to introduce any breaking changes. 

With this stuff updated should be a step further in the right direction for 7.2.5.

**Comment by Shazwazza** [comment]
Just FYI, I've updated the codebase in 7.3 to no longer cast! So this should be possible in the 7.3 core now. I'd be very interested to hear how your journey goes with this and if there's anything i can help out with.

http://issues.umbraco.org/issue/U4-6484

**Comment by CGaskell** [comment]
Hey Thomas,

I have integrated elastic search with umbraco previously by taking items out of the published content xml table, creating dynamic objects from that XML and indexing them to ES via NEST. I spoke with Shannon at CodeGarden and he mentioned you had started work on a provider (rather than this external indexing method).

I wondered if you were sharing your code or if there was any way I could help - I'm very interested in getting ES working with Umbraco almost put of the box.

Cheers
