### ISSUE TITLE
Make Examine .NET Standard Package?

### ISSUE THREAD

**Issue by bielu** [Shazwazza/Examine#141]
Hi @Shazwazza,
I was looking on dependencies of Examine as soon we will upgrade to 4.8 we are not really using any dependency which is not available as .NET Standard Package. What do you think about Start Work on making it .NET Standard?

**Comment by Shazwazza** [comment]
Yep once it's running 4.8 it should definitely be a .NET Standard package.

**Comment by cleversolutions** [comment]
@Shazwazza want help migrating to 4.8? I have maybe a couple hours a week I can dedicate, but it's improving now that my kids are sleeping. Also I'll be building on a Mac, so .NET Standard all the way.

**Comment by bielu** [comment]
@cleversolutions actually you should look into prs which are opened and it is here 2:
Move to 4.8
Make .net standard implementation
And next week I am going to finish azure directory in 1 one which means we will move to work on second one😉

**Comment by cleversolutions** [comment]
Too awesome @bielu 🙌

**Comment by marciogoularte** [comment]
Hello guys. For those interested, this past weekend I ported the exam to Lucene 4.8 (beta 12) and .NET Standard.

So far it is working very well. I did it from the .net core branch.

so far it's doing very well in the tests. Only MultiIndexSearcher that I couldn't do. I removed several override methods that are no longer used in version 4.8.

Also the OpenReaderTracker that didn't make sense.

**Comment by Shazwazza** [comment]
@marciogoularte awesome! @bielu has also pushed a PR for this here https://github.com/Shazwazza/Examine/pull/140#issue-332544991 and here https://github.com/Shazwazza/Examine/pull/151

I haven't got around to reviewing but I do plan on this soon since we need it for umb netcore soon. Any chance you could review and/or compare what you've done with these PRs? Or are you saying that you used these PRs to do your work?
