### ISSUE TITLE
Example code for checking health and reindexing

### ISSUE THREAD

**Issue by JohnBergman** [Shazwazza/Examine#142]
I was wondering if you could point me to some code or docs related to determining the health of the indexes and possibly reindexing?  We have an umbraco instance (posted for help to find a solve elsewhere) that tends to have corrupted indexes fairly often running on azure.  I was going to write a monitor that would at least alert of that condition, if not take action to cause a reindex.

**Comment by Shazwazza** [comment]
Sounds like you are looking for a work around to an underlying problem. .. which is why are your indexes getting corrupted. If you are running on Azure there's a bunch of specialized setup required for you to do. Have you seen these docs and have the right config in place? https://our.umbraco.com/documentation/Getting-Started/Setup/Server-Setup/azure-web-apps

**Comment by JohnBergman** [comment]
(I agree) - Yes, We are configured as specified per the setup documentation.  I have verified it multiple times to be sure something has not crept in.  I am happy to post the config files or provide any other information to help identify what the underlying issue is.

**Comment by JohnBergman** [comment]
(This is the post over on the Our.Umbraco site) looking for help in resolving the root cause of the corruption.  https://our.umbraco.com/forum/using-umbraco-and-getting-started//99940-examine-indexes-get-corrupted-or-need-to-be-rebuilt-frequently-document-cache-not-always-updated

**Comment by Shazwazza** [comment]
I will close this question and leave the details on the forum post.
