### ISSUE TITLE
what does Examine think about websites with huge number of nodes?

### ISSUE THREAD

**Issue by MosabAbuzaid** [Shazwazza/Examine#148]
Hi Shanon 
I am using examine search with a newspaper website that have to publish more than 500 nodes daily 
and i have more than one million node to search in them with examine.
i have some fears with a huge amount of nodes so i chick the app data folder size and i found that i will have 10 GB almost in the app data folder when i publish the first 200000 node so i think that i will have more than 100 GB at end. 
i also take a look inside the app data folder and see that internal index and external index split that into s small files but in nuchash i have just 3 files.
so what does examine think about a huge size in nucash? is that will affect the examine search speed    or slow my website ?

**Comment by Shazwazza** [comment]
Sounds like something you should be able to test locally. I don't have personal experiene with indexes that large. Lucene and nucache are totally different things so you can't compare them. Lucene manages it's own files, lucene is an additive process. When lucene decides to optimize the index files, it will and you will be left with fewer larger files, but this is just how lucene works internally. Searching shouldn't be slower the larger the index you have but of course rebuilding an index of that size will take a very long time... not because of Lucene/Examine but because of the overhead to lookup all of that data. As far as I know there is no limitations to how large an on disk lucene index is and they way that Lucene works shouldn't change it's performance with larger indexes. But I would suggest this is something you should be testing locally.
