### ISSUE TITLE
MultipleCharacterWildcard() does not escape value

### ISSUE THREAD

**Issue by ronaldbarendse** [Shazwazza/Examine#187]
Because the `MultipleCharacterWildcard()` (and probably also `SingleCharacterWildcard()`) extension method don't escape the value, it throws an `ParseException: '*' or '?' not allowed as first character in WildcardQuery` in the following example:

```c#
var term = "*es";
var query = searcher.CreateQuery(IndexTypes.Content)
    .GroupedOr(new[] { "nodeName" }, term.Escape(), term.MultipleCharacterWildcard());

query.Execute();
```

To fix this, you have to manually escape the value using `QueryParser.Escape(term).MultipleCharacterWildcard()`, but that should actually be done here:

https://github.com/Shazwazza/Examine/blob/db6ad8af0681d4a3112e6f299b33401783cfbb1d/src/Examine/LuceneEngine/Search/LuceneSearchQueryBase.cs#L317-L320

If other `IExamineValue`/`Examineness` types have the same issue, those could also be updated to correctly escape the value.

**Comment by stefankip** [comment]
This might also be related to this issue I created at the Umbraco repo: https://github.com/umbraco/Umbraco-CMS/issues/8991

**Comment by Shazwazza** [comment]
Yep it definitely is. Just need to write a test or two to confirm that @ronaldbarendse PR is the correct thing to do

**Comment by Shazwazza** [comment]
So this can't quite work this way unfortunately. For example, we have a path query like `var wildcardfilter = wildcardcriteria.Field("__Path", "-1,123,456,".MultipleCharacterWildcard());` and by escaping the value here it will fail. We cannot just escape all values there.

Another reason this can't work this way is that "*es" may be an actual wildcard query if you have prefixed wildcard queries enabled.

The specific error you are getting is this one: https://github.com/apache/lucenenet/blob/849f244201619ca90099b5e1fafa81c4cd2fbc7e/src/core/QueryParser/QueryParser.cs#L996 

In which case we can handle this specific case in our CustomMultiFieldQueryParser and override the GetWildcardQuery

@stefankip though related, the issue you logged in Umbraco https://github.com/umbraco/Umbraco-CMS/issues/8991 isn't quite the same because Umbraco's back office search uses a `NativeQuery` search using a built up lucene string.  Because that is using raw lucene syntax, the fix would have to be applied in Umbraco.

**Comment by Shazwazza** [comment]
@ronaldbarendse I've pushed a new branch with a test and updated code to deal with this specific case https://github.com/Shazwazza/Examine/tree/bugfix/prefixed-special-chars

But it's not working as expected so if you feel like taking a look please do. The fix is doing the correct thing but being able to search on values with prefixed wildcards when not being treated as wildcards is not working. 

Here is the commit: https://github.com/Shazwazza/Examine/commit/dde644bd8e971e3e48f017d6c0d1398d8486c8fd and here is the TODO: https://github.com/Shazwazza/Examine/commit/dde644bd8e971e3e48f017d6c0d1398d8486c8fd#diff-1513fc5638e596798f66cb7126b250925c2eb6d83d2ed8b77c16377f3d1846cdR60

I cannot make this query work and not really sure why. The fix to deal with prefixed wildcard chars while AllowLeadingWildcard is false to avoid this exception. I don't have much time to spend on this edge case so am hoping for some help 🙏
