### ISSUE TITLE
Examine Custom Index is not getting rebuilt every time I publish a node

### ISSUE THREAD

**Issue by tkardaridis** [Shazwazza/Examine#199]
Hi,

I created a custom examine index following yours [example](https://gist.github.com/Shazwazza/3d32f4f37d9adadfe56400d0c24db6bd) in order to use the custom fields of a document type and also to order by a custom date instead of the default updateDate. Everything works fine.

Now i am using CMSImport, to import content to my site. From what i saw, the ExternalIndex is getting refreshed but the Custom index not. When i unpublish or publish a content, the ExternalIndex documents number is getting updated, nor the CustomIndex.

So, do i have to force reindex on publish and unpublish manually? And if yes, do i have to subscribe to events like the following example?

https://our.umbraco.com/documentation/getting-started/Code/Subscribing-To-Events/

/Thomas

**Comment by tkardaridis** [comment]
How the ExternalIndex is getting refreshed on every publish and unpublish, even more on massive imports using CMSImport? I created a component to rebuild my index on ContentSevice.Published and ContentSevice.UnPublished as follows

`[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class SubscribeToNewsArticleIndexRefreshComposer : ComponentComposer<NewsArticleIndexRefreshComponent>
    {
        //this automatically adds the component to the Components collection of the Umbraco composition
    }

    public class NewsArticleIndexRefreshComponent : IComponent
    {
        private readonly ILogger _logger;
        private readonly IExamineManager _examineManager;
        private readonly IndexRebuilder _indexRebuilder;
        private readonly IAppPolicyCache _runtimeCache;

        public NewsArticleIndexRefreshComponent(ILogger logger, IExamineManager examineManager, AppCaches appCaches, IndexRebuilder indexRebuilder)
        {
            _logger = logger;
            _examineManager = examineManager;
            _indexRebuilder = indexRebuilder;
            _runtimeCache = appCaches.RuntimeCache;
        }

        // initialize: runs once when Umbraco starts
        public void Initialize()
        {
            // subscribe to content service published event
            ContentService.Published += ContentService_Published;
            ContentService.Unpublished += ContentService_Unpublished;
        }

        // terminate: runs once when Umbraco stops
        public void Terminate()
        {
            // unsubscribe on shutdown
            ContentService.Published -= ContentService_Published;
            ContentService.Unpublished -= ContentService_Unpublished;
        }

        private void ContentService_Published(Umbraco.Core.Services.IContentService sender, Umbraco.Core.Events.ContentPublishedEventArgs e)
        {
            RebuildIndex();
        }

        private void ContentService_Unpublished(Umbraco.Core.Services.IContentService sender, Umbraco.Core.Events.PublishEventArgs<Umbraco.Core.Models.IContent> e)
        {
            RebuildIndex();
        }

        private void RebuildIndex()
        {
            bool validated = ValidateIndex("NewsArticleIndex", out var index);
            if (!validated)
                return;

            validated = ValidatePopulator(index);
            if (!validated)
                return;

            _logger.Info<NewsArticleIndexRefreshComponent>("Rebuilding index '{IndexName}'", index.Name);

            //remove it in case there's a handler there already
            index.IndexOperationComplete -= Indexer_IndexOperationComplete;

            //now add a single handler
            index.IndexOperationComplete += Indexer_IndexOperationComplete;

            try
            {
                //clear and replace
                index.CreateIndex();

                var cacheKey = "temp_indexing_op_" + index.Name;
                //put temp val in cache which is used as a rudimentary way to know when the indexing is done
                _runtimeCache.Insert(cacheKey, () => "tempValue", TimeSpan.FromMinutes(5));

                _indexRebuilder.RebuildIndex(index.Name);
            }
            catch (Exception ex)
            {
                //ensure it's not listening
                index.IndexOperationComplete -= Indexer_IndexOperationComplete;
                _logger.Error<NewsArticleIndexRefreshComponent>(ex, "An error occurred rebuilding index");
            }
        }

        private bool ValidateIndex(string indexName, out IIndex index)
        {
            if (!_examineManager.TryGetIndex(indexName, out index))
            {
                _logger.Error(GetType(), "NewsArticleIndexRefreshComponent | | Message: {0}", $"No index found by name < NewsArticleIndex >");
                return false;
            }

            return true;
        }

        private bool ValidatePopulator(IIndex index)
        {
            if (_indexRebuilder.CanRebuild(index))
                return true;

            _logger.Error(GetType(), $"The index {index.Name} cannot be rebuilt because it does not have an associated {typeof(IIndexPopulator)}");
            return false;
        }

        private void Indexer_IndexOperationComplete(object sender, EventArgs e)
        {
            var indexer = (IIndex)sender;

            _logger.Debug<NewsArticleIndexRefreshComponent>("Logging operation completed for index {IndexName}", indexer.Name);

            //ensure it's not listening anymore
            indexer.IndexOperationComplete -= Indexer_IndexOperationComplete;

            _logger.Info<NewsArticleIndexRefreshComponent>($"Rebuilding index '{indexer.Name}' done.");

            var cacheKey = "temp_indexing_op_" + indexer.Name;
            _runtimeCache.Clear(cacheKey);
        }
    }`

And in order the CustomIndex is getting the data from a GetAll() function which is

 `public List<NewsArticle> GetAll()
        {
            try
            {
                using (UmbracoContextReference umbracoContextReference = _umbracoContextFactory.EnsureUmbracoContext())
                {
                    IPublishedContentCache contentHelper = umbracoContextReference.UmbracoContext.Content;
                    var publishedArticles = contentHelper.GetByXPath("//homeDocType/newsCategory/newsArticle")?.ToList();
                    if (publishedArticles != null)
                    {
                        var results = publishedArticles.Select(x => (NewsArticle)x).Where(x => x.IsPublished() && x.IsVisible()).ToList();
                        return results;
                    }
                    return null;
                }

                //To slow
                //var results = Services.ContentService.GetByLevel(3).Where(c => c.Published).ToList();
                //return results;
            }
            catch (Exception e)
            {
                _logService.Error(GetType(), "Search | Exception: {0} | Message: {1}", e.InnerException != null ? e.InnerException.ToString() : "", e.Message != null ? e.Message.ToString() : "");
            }

            return null;    
        }`

But unfortunately on the following line, I am getting a Null reference exception, probably the IPublishedCache is not available due to the publishing procedure? I don't really know

    `var publishedArticles = contentHelper.GetByXPath("//homeDocType/newsCategory/newsArticle")?.ToList();`

So how the ExternalIndex is getting refreshed without locks and problems on publish and unpublish?

**Comment by Shazwazza** [comment]
Please do not rebuild indexes. This is an anti-pattern and is terrible for performance. 

> How the ExternalIndex is getting refreshed on every publish and unpublish

Umbraco is in control of this, it listens to umbraco events and updates the index. Examine is just an index/search engine, it doesn't know about Umbraco, Umbraco tells it what to do.

There are a ton of events to consider for this you are best to not try to duplicate this.

Based on your description though, it sounds like you are creating a custom index for Umbraco data?? If so, why? Umbraco is already engineered to handle that. It will index all content in the Externalndex. If you want to customize that index, go for it but really in most cases you shouldn't need additional Umbraco based indexes. This is also not good for performance. If you really really want to have a secondary Umbraco based data index, you would just create an additional `UmbracoContextIndex`. You don't have to manually create an index like the example you linked to, nor handle anything else, it will just be managed by Umbraco. That example is for external/custom/non-umbraco data sources.

I will close this since this is an Umbraco specific question. The Umbraco forum is a great place to ask Umbraco question: https://our.umbraco.com

**Comment by tkardaridis** [comment]
Well i really need to create a custom index for specific properties of my
document types because, for example, Umbraco indexes the DateTime Picker of
a Document Type property as FullText which is wrong. I cannot make range
query with that. Also i want to remove the time part of the index and keep
only the date something that it cannot be done using ExternalIndex of
umbraco. I will check if by creating a can resolve the issue
UmbracoContextIndex with the rebuild on Publish and Unpublish event.

Best regards,

*Thomas S. Kardaridis*
M: +30 6948200035
E: t.kardaridis@hotmail.com | t.kardaridis@gmail.com

**Comment by Shazwazza** [comment]
> Umbraco indexes the DateTime Picker of a Document Type property as FullText which is wrong

You can entirely customize the built in index to your needs. You can completely control the an index value per field is indexed and what goes in there (via events).

* https://our.umbraco.com/Documentation/Reference/Searching/Examine/indexing/
* https://our.umbraco.com/Documentation/Reference/Searching/Examine/indexing/#changing-field-value-types
* https://shazwazza.github.io/Examine/configuration.html

If you use UmbracoContextIndex  you should not do anything with events and please do not ever rebuild based on events. You should never need to bind to events for Umbraco based data for indexes, this is all done for you. But i would still suggest not creating additional indexes since you should be able to modify and use the built in one for most purposes. For reference, this is done here https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Search/ExamineComponent.cs#L118
