### ISSUE TITLE
Examine query problem

### ISSUE THREAD

**Issue by SRandomName** [Shazwazza/Examine#200]
Hello !

i'm running into some issues trying to create a Examine Query.

In my custom index I have a field called 'TestTaxonomy' (A MNTP with only 1 doc type allowed) with for example the following values: umb://document/75e97ba7f01c4723a258a243bf813a1c,umb://document/e936faa0f0eb4c62aeb993de3351a1f4

In this value I would like to be able to search 1 value and return the item if the value is found.

My current query:
`var results = _newsIndexSearcher.CreateQuery(IndexTypes.Content, BooleanOperation.Or)
            .GroupedOr(new string[] { "TestTaxonomy_" + _currentCulture }, allThemesUdis.ToArray())
            .Not().Field("__nodeId", newsItemId)
            .OrderByDescending(new SortableField("createDate"))
            .Execute(4);`
This query works if my 'TestTaxonomy' field only has 1 value, however it goes wrong when there are more then 1 values.

Examples in screenshot

Any ideas ? Thanks in advance !

![image](https://user-images.githubusercontent.com/48089189/102055594-62417d00-3deb-11eb-90c9-ebb2812d0bd3.png)

**Comment by Shazwazza** [comment]
What version are you using?

If you have a look at the FluentApi tests in this project, there are tons of query examples, along with easy ways to setup unit tests. That is probably the best way to figure out what is going on. I'd also start with simplicity, like remove the Not query, search on a single field instead of GroupedOr, etc... make sure the simplest thing works and then add complexity. 

Also depends on how you are indexing TestTaxonomy (i.e. what field type it is). If you haven't changed it then it's using full text field type which will be using `CultureInvariantStandardAnalyzer` and since you are dealing with UDIs that's probably not what you want since they contain special characters. You would probably also want to escape the UDI value you are searching but you are just passing in the array of UDIs as-is.

**Comment by Shazwazza** [comment]
(Closing this since it's just a question)
