### ISSUE TITLE
How to get  IndexSearcher object from lucene index/_examineManager?

### ISSUE THREAD

**Issue by sayedgt** [Shazwazza/Examine#257]
To create join query I need to pass indexSearcher object in  JoinUtil.CreateJoinQuery() method. How will I get this indexSearcher?
```Query joinQuery = JoinUtil.CreateJoinQuery(fromField: "ID", multipleValuesPerDocument: true,
                toField: "c_id", fromQuery: fromQuery, **Lucene.net IndexSearcher object**, ScoreMode.Avg);

```

**Comment by Shazwazza** [comment]
Depending on what you need to do.... 

* To resolve the IndexSearcher, you can resolve that Lucene object by casting the IIndex.Searcher property to [`LuceneSearcher`](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Lucene/Providers/LuceneSearcher.cs). This then exposes a method [`GetSearchContext`](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Lucene/Providers/LuceneSearcher.cs#L33) which returns a `ISearchContext`. This has a method `GetSearcher()` which returns a `ISearcherReference` (which will need to be disposed by you) which has a property `IndexSearcher` that returns the underlying Lucene `IndexSearcher`
* You can also resolve the Lucene index writer objects by casting the `IIndex` to the underlying [`LuceneIndex`](https://github.com/Shazwazza/Examine/blob/dev/src/Examine.Lucene/Providers/LuceneIndex.cs) type. This exposes a public property [`IndexWriter`] of a Lucene type called `TrackingIndexWriter` which has a `IndexWriter` property. Be careful to not dispose of these instances or modify them because they are managed by Examine. Any reader or searcher you create from this will need to be managed by you.
