### ISSUE TITLE
How to create Field Definitions outside of options?

### ISSUE THREAD

**Issue by LabWorksDigital-Tech** [Shazwazza/Examine#259]
In version 1, I was able to dynamically add field definitions into an existing index using the code below:
`index.FieldDefinitionCollection.AddOrUpdate(new FieldDefinition(name, FieldDefinitionTypes.Double))`

Is there a way for me to do something similar in v2 outside of configuring the field definition using IOptions?

**Comment by Shazwazza** [comment]
Hi, no IOptions is the only way to configure the index. All setup is done during service configuration. Previously this was problematic since you couldn't actually do this at runtime since it would have no effect once the index was initialized. Using IOptions should suffice for all index configuration.

**Comment by LabWorksDigital-Tech** [comment]
Thanks for the clarification. We are able to implement what we had to do by using the IOptions route.
