### ISSUE TITLE
Make ValueSet immutable

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Examine#276]
This is to resolve the issue of the ValueSet changing in one index's validation process while another is processing it.

* https://github.com/SDKits/ExamineX/issues/53
* https://github.com/umbraco/Umbraco-CMS/issues/4480

Will also mean that IValueSetValidator will change

**Comment by Shazwazza** [comment]
@bergmania this is the breaking change and Umbraco source will need to be updated to accommodate this. Essentially means that:

* Implementations of IValueSetValidator will need to be updated
* If the ValueSet is filtered, then the result of IValueSetValidator  will be a new ValueSet with the filtered values, else if it's not filtered then there is no need to clone the ValueSet

**Comment by bergmania** [comment]
@Shazwazza Currently we use the `OnTransformingIndexValues` event to update the value set. How would you recommend doing the same thing now?


```cs
protected override void OnTransformingIndexValues(IndexingItemEventArgs e)
{
    base.OnTransformingIndexValues(e);
    
    //ensure special __Path field
    var path = e.ValueSet.GetValue("path");
    if (path != null)
    {
        e.ValueSet.Set(UmbracoExamineFieldNames.IndexPathFieldName, path);
    }

    //icon
    if (e.ValueSet.Values.TryGetValue("icon", out var icon) && e.ValueSet.Values.ContainsKey(UmbracoExamineFieldNames.IconFieldName) == false)
    {
        e.ValueSet.Values[UmbracoExamineFieldNames.IconFieldName] = icon;
    }
}
```

**Comment by Shazwazza** [comment]
Yep good catch, I'll need to update the event args to be able to set a new ValueSet

**Comment by Shazwazza** [comment]
@bergmania  I've just pushed a change allowing the `IndexingItemEventArgs.ValueSet` property to be get/set. So if you want to modify the ValueSet, you would re-assign the ValueSet property on the event args.

**Comment by bergmania** [comment]
@Shazwazza, thanks, but it seems like that change is not enough. You also need to use the `ValueSet` from the event e.g. in `ProcessIndexQueueItem` now that it potentially is a different `ValueSet`.

**Comment by ronaldbarendse** [comment]
@bergmania Had a quick look after our discussion and updating values should be possible with the following changes:

1. Make the `ValueSet` of the event argument settable (possibly with some additional null-guards), so the event handlers can construct a new instance with updated values to replace the existing one `public ValueSet ValueSet { get; set; }`:
https://github.com/Shazwazza/Examine/blob/eb47232e2a434e86769199bb30fffc9b27d2f109/src/Examine.Core/IndexingItemEventArgs.cs#L8

2. Use the `ValueSet` from the event argument to add the document `AddDocument(d, indexingNodeDataArgs.ValueSet);`: "
https://github.com/Shazwazza/Examine/blob/eb47232e2a434e86769199bb30fffc9b27d2f109/src/Examine.Lucene/Providers/LuceneIndex.cs#L1088

Depending on how the `IndexOperation` is used later, you might want to set the `ValueSet` to the updated instance too (and keep the existing ` AddDocument(d, op.ValueSet);`, as that's then referencing the same instance again).

**Comment by bergmania** [comment]
https://github.com/Shazwazza/Examine/pull/277

**Comment by Shazwazza** [comment]
Nice, and have made @ronaldbarendse 's suggested change of having the SetValues method

**Comment by Shazwazza** [comment]
@bergmania have pushed Examine 3.0.0-beta.9 to nuget

**Comment by ronaldbarendse** [comment]
One downside to the current implementation is that it requires creating/allocating new dictionaries in each event handler to set the updated `ValueSet`...

Maybe it's better to add an `IDictionary<string, IEnumerable<object>> TransformedValues { get; }` property to the `IndexingItemEventArgs`, that is created once and each event handler can modify?

**Comment by Shazwazza** [comment]
@ronaldbarendse that could probably work, any chance you have time to send a PR?

**Comment by bergmania** [comment]
@Shazwazza any ETA of the final Examine 3.0.0?

**Comment by Shazwazza** [comment]
Is Monday ok?

**Comment by bergmania** [comment]
> Is Monday ok?
@Shazwazza, That's perfect, thank you in advance 💪

**Comment by ronaldbarendse** [comment]
> @ronaldbarendse that could probably work, any chance you have time to send a PR?

I did start on adding the additional `TransformedValues` property, but that would actually always require creating a copy of the values _and_ a new `ValueSet` instance again, even when you don't transform the values...

I then dug a bit more into why the following is done in v2:

https://github.com/Shazwazza/Examine/blob/a7908b8e2613f93f1447f52730e1eccf37a0a602/src/Examine.Lucene/Providers/LuceneIndex.cs#L707-L711

From what I understand, if the same `ValueSet` instance (with the same `Values` dictionary) is passed into multiple indexes, `IIndex.IndexItems()` would use this instance in the `TransformingIndexValues` event and only afterwards create a copy of the values, just before adding them to the index. Besides the fact that the `TransformingIndexValues` could then be invoked on an already transformed instance, copying the values only minimizes the chance of the `Collection was modified; enumeration operation may not execute.` exception, because that's done faster then iterating the original values and adding them to the index. You could still get this exception if a `TransformingIndexValues` event changed the values while the copy was being made, right?

If you would create a copy of the `ValueSet` before the values are transformed, the `TransformingIndexValues` would always get a unique instance with the original values and that should solve the issue without adding major breaking changes to v3: https://github.com/Shazwazza/Examine/pull/282.

**Comment by bergmania** [comment]
@Shazwazza, I agree with you.
From a selfish / Umbraco perspective, I also prefer that we continue with what has now been tested in RC for a month.

**Comment by Shazwazza** [comment]
Ok, I'll release it as-is

**Comment by bergmania** [comment]
> Ok, I'll release it as-is

Amazing.. Please ping me when it is on NuGet. Currently I'm refreshing NuGet all the time 🙈

**Comment by Shazwazza** [comment]
The package is in the artifacts in the Actions tab for version 3.0.0, will be the same files I upload this morning, but that will be later for you

**Comment by Shazwazza** [comment]
It's pushed to nuget now
