### ISSUE TITLE
Support of Lucene 3.0.3 and .net 4.5

### ISSUE THREAD

**Issue by ioriyenko** [Shazwazza/Examine#30]
Current version of Examine built on top of Lucene 2.9.4.1 and target .net framework is 4.0
It would be nice to have it built on top of the latest verion of Lucene (currently 3.0.3) and .net v4.5.1

**Comment by Shazwazza** [comment]
It will be in version 2, Latest Lucene versions have large breaking changes. Examine v2 will be shipped with Umbraco v8 next year.

Examine v2 can be trialed in beta now https://github.com/Shazwazza/Examine/releases/tag/untagged-384de2e09fb901aed7ad ... but it is not compatible with any Umbraco sites because of the large breaking changes between Lucene 2 and 3.
