### ISSUE TITLE
GroupedOr with a boosted stop word causes an Object Null Reference 

### ISSUE THREAD

**Issue by bowserm** [Shazwazza/Examine#34]
I ran into a problem today where if I boosted a stop word and passed it to a GroupedOr, it would explode with an Object Null Reference Exception in Examine.LuceneEngine.SearchCriteria.LuceneSearchCriteria line 308.

I was using Umbraco 7.1.8. I haven't had time to see if there are easier ways to reproduce.

This is a trimmed down, example version of the code I was using to cause the problem.
`var searchPhrase = "the united states";`
`var searchTerms = searchPhrase.RemoveStopWords().Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);`
`var siteSearcher = ExamineManager.Instance.SearchProviderCollection["ExternalSearcher"];`
`var searchCriteria = siteSearcher.CreateSearchCriteria(BooleanOperation.Or);`
`var query = searchCriteria.GroupedOr(new [] {"nodeName", "navigationTitle"}, searchTerms.Select(t => t.Boost(10)).ToArray());`

In case anyone runs into this, the quick word around is to use this cool string extension method I found called `RemoveStopWords()`. You can just strip the stop words out before you search with them.

**Comment by TomSteer** [comment]
Hey @Shazwazza Is there any update on this bug? Cheers, Tom

**Comment by Shazwazza** [comment]
Why not just use the workaround described above? 

The problem is that it depends on what analyzer is being used to search with, so i can't just always strip stopwords from search terms because people might be using a different analyzer that requires stop words and there's no real way of knowing which analyzers would throw since people can make or use any analyzers they want.

**Comment by TheBekker** [comment]
For other people coming by this issue:
Worth noting that "RemoveStopWords()" uses the StandardAnalyzer, so wont work if you use some other analyzer. (So the method name could be a bit misleading)

**Comment by ainteger** [comment]
If I using StandardAnalyzer, searching for a term with only stop words without doing any commands to remove those, my query will throw a null exception. Because this are made in layer inside Examine I think it should be treated as a bug. A raw query will not throw this exception so we have different behaviors now.

(The non-global approach with english as default in Lucene is another question...)
