### ISSUE TITLE
Umbraco Examine internal index becomes corrupt regularly

### ISSUE THREAD

**Issue by mihaela-radu** [Shazwazza/Examine#39]
Hi,

On an Umbraco 7.3.2 instance with Examine 0.1.68 installed, we have the out of the box internal index set up:

ExamineIndex.config:

`
	
	<IndexSet SetName="InternalIndexSet" IndexPath="~/App_Data/TEMP/ExamineIndexes/Internal/"/>`

ExamineSettings.config:

`
<ExamineIndexProviders>	
<providers>
			<add name="InternalIndexer" type="UmbracoExamine.UmbracoContentIndexer, UmbracoExamine"
				 supportUnpublished="true"
				 supportProtected="true"
				 analyzer="Lucene.Net.Analysis.WhitespaceAnalyzer, Lucene.Net"/>
</providers>
</ExamineIndexProviders>`
`<ExamineSearchProviders defaultProvider="ExternalSearcher">
<providers>
			<add name="InternalSearcher" type="UmbracoExamine.UmbracoExamineSearcher, UmbracoExamine"
				 analyzer="Lucene.Net.Analysis.WhitespaceAnalyzer, Lucene.Net" enableLeadingWildcard="true" enableDefaultEventHandler="true"/>
</providers>
	</ExamineSearchProviders>
`
We have enabled wildcard search and updates on content saving for this internal index using these settings:
enableLeadingWildcard="true" 
enableDefaultEventHandler="true"

This works fine most of the time but then it stops working completely, with no error in the logs. We can see the index has become corrupt because searching fo some content in Umbraco brings no results back. After doing a full site republish the issue gets fixed and the index is back to normal, but this happens regularly.

Is there something we can do to stop the internal index becoming corrupt?

Thank you.

**Comment by Shazwazza** [comment]
What you do you mean by 'corrupt', unreadable or empty or what? have you seen this: https://our.umbraco.org/forum/developers/extending-umbraco/74731-examine-corruption-issues

I'd need to know about your environment, Azure, load balanced, something else etc... This is most likely an environment + Umbraco question than a base Examine library question.

**Comment by mihaela-radu** [comment]
When I say corrupt, I mean unreadable because the Umbraco internal search returns no results from it. I'm waiting for this to happen again so I can grab a copy of the actual index and look at its content with Luke.

The setup is the simplest: single site on single server, CMS and front end on the same site.

Thanks.

**Comment by Shazwazza** [comment]
If it was corrupt, you would get YSODs since it wouldn't read anything (and luke would also not be able to read it) and you would have errors in your logs. If it's returning nothing its means its most likely empty.  Is your server virtualized? or anything like that ? any other info, custom event handlers that do anything to the indexes, etc... ?

**Comment by anthony-gledhill-e3** [comment]
The server virtualised and running on VMWare. There are no other custom events that we run on the code when indexing the data. 

The API call is to 
umbraco/backoffice/UmbracoApi/Entity/Search?query=Third&type=Document&searchFrom=2104  
and we are pointing to the right node and there are no details in the TraceLog

**Comment by Shazwazza** [comment]
@tony-e3 is your issue *Exactly* the same as @mihaela-radu (or are you guys working together)? Please, when reporting issues provide all details: Versions, environment info, steps to reproduce, etc...  the more info the better otherwise it's much more difficult to assist.

From the above, if your index is *Empty* then it will be readable by Luke but will just contain zero documents ... is this the case? If not, what information is actually in your index?

Also note, you should really be using the latest version of Umbraco, in fact there are some index/examine fixes in later versions than 7.3.2

**Comment by mihaela-radu** [comment]
Hi @Shazwazza, @tony-e3  is my colleague and I asked him to provide you with answers to what you asked above. So yes, we are both talking about the same website.

The index is not empty, I had a look at it today, everything is in it, it is probably the internal Umbraco search that fails to get things out of it by whatever criteria it is using - like I said, a full republish fixes it temporarily.

Upgrading would be a major job just to fix this issue, but thanks for suggesting.

Mihaela.

**Comment by Shazwazza** [comment]
OK at least I know you guys are talking about the same thing.

If the index is not empty but it's just missing content items that is a *much* different thing than the index being cleared (=empty) or becoming corrupted (=not open-able or readable with exceptions). 

If "everything is in it", can you confirm that the exact item that you are querying for exists there? If so, then how are you querying with Examine? Can you query with Luke with the correct results?

Otherwise if the item you want to find isn't in your index but you think it should be then if you change your log level in log4net settings to Debug then Examine will log the details of what is being indexed or deleted which might help you figure out the issue.  Also, sounds like you are using the Internal index for external searches which is not recommended because the internal index includes non-published items ... this is the reason the external index is declared in config by default. In order to determine why you have an issue you are going to need to replicate the problem (preferably in a local environment) somehow or determine when exactly it occurs and check your logs for details. Since the index isn't empty i can only assume that the item gets deleted from the index.

Upgrading umbraco is a seamless process, it is very easy to upgrade i don't see why this would be an issue unless you haven't mentioned all of the details of your environment (i.e. load balancing, etc.. )

I would also suggest putting these details on http://our.umbraco.org since this is really an Umbraco issue - not Examine core.

**Comment by mihaela-radu** [comment]
Thanks @Shazwazza.

The issue is not with the site search, it is actually with the internal Umbraco search implemented by Umbraco for using in the CMS backend to find content. 

We might raise it with Umbraco next as suggested.

Thanks again.
