### ISSUE TITLE
When using German Analyzer for SearchProvider and IndexProvider, query is incorect.

### ISSUE THREAD

**Issue by aburok** [Shazwazza/Examine#54]
Hi,

When using ***GermanAnalyzer*** for search provider, the ***LuceneBooleanOperation*** *Compile()* method is generating query that looks like this:
{ SearchIndexType: **content**, LuceneQuery: +(+(contents:**searchedword**\*)) +\_\_IndexType:**con** }

In the other hand, the ***StandardAnalyzer***, which is being used for English language, as search provider, generate following query:
{ SearchIndexType: **content**, LuceneQuery: +(+(contents:**searchedword**\*)) +\_\_IndexType:**content** }

After further investingation, it seems that the field *__IndexType* is being tokenized and stemmed by the ***GermanAnalyzer***. So from word **content** we get word **con**.
With search condition __IndexType:**con**, Lucene will return 0 results, as the [__IndexType](https://github.com/Shazwazza/Examine/blob/master/Projects/UmbracoExamine/IndexTypes.cs) has only phrase : *content* or *media*.

I'm not sure how to fix it, as the project is complex. 
After brief investigation I've found that [following line](https://github.com/Shazwazza/Examine/blob/223f425c29138091ba51d6cbb5d735d549d91d5a/Projects/UmbracoExamine/SearchCriteria/LuceneBooleanOperation.cs#L62) is missing a 4th parameter, that would prohibit this field from being analyzed:

`
this.search.FieldInternal(
    LuceneExamineIndexer.IndexTypeFieldName, 
    new ExamineValue(Examineness.Explicit, this.search.SearchIndexType.ToString().ToLower()), 
    BooleanClause.Occur.MUST);
`

I've a work around for this now, but it is hacky. 
When I will have some spare time I will try to create pull request.

**Comment by Shazwazza** [comment]
Thanks for the info! There's probably a reasonably easy fix for this, hopefully i can find some time next week to have a look

**Comment by aburok** [comment]
Versions that I used:  
<package id="Examine" version="0.1.68.0" targetFramework="net451" />
<package id="Lucene.Net" version="2.9.4.1" targetFramework="net451" />
<package id="Lucene.Net.Contrib" version="2.9.4.1" targetFramework="net451" />

**Comment by Shazwazza** [comment]
If I pass in a `false` to the FieldInternal, it will not use the QueryParser to contruct the query - and that will work because it's just an explicit string concat. The __IndexField is definitely configured to not be analyzed, etc... when it gets indexed, however I suppose the QueryParser doesn't actually know about that. The QueryParser used is just an instance of `MultiFieldQueryParser` but it isn't aware how all of the fields are configured so I guess this is why this happens. 

You can see here that this is the method that returns 'special' fields : https://github.com/Shazwazza/Examine/blob/master/Projects/Examine/LuceneEngine/Providers/LuceneIndexer.cs#L1323

which includes `__IndexType` and here's where the code is that is going to index these fields: 
AddSpecialFieldsToDocument
https://github.com/Shazwazza/Examine/blob/master/Projects/Examine/LuceneEngine/Providers/LuceneIndexer.cs#L1747


In any case, I'm not sure it is possible to configure the QueryParser or use a different QueryParser to know about all of the different field rules so I think it's safe to just use the false overload to be explicit.

Thanks for finding this ! :)

**Comment by ismailmayat** [comment]
Shannon,

Similiar issue when doing pdf search using french analyser, so media is stemmed to medi and then query becomes +__IndexType:medi and hence you get no results
