### ISSUE TITLE
Getting total count from search without loading all results into memory

### ISSUE THREAD

**Issue by mahgo** [Shazwazza/Examine#58]
I was wondering if it is possible to get the total number of results from the search query without loading all results into memory? My understanding is that BaseSearchProvider.Search() will load everything into memory, is this correct? 

My main use for this is for paging.

**Comment by Shazwazza** [comment]
yes definitely, The resulting ISearchResult contains this value: https://github.com/Shazwazza/Examine/blob/master/Projects/Examine/ISearchResults.cs#L10

if you are doing paging you must also ensure to use Examine's own `Skip` method because this will instruct Lucene directly to perform the Skip, if you use Linq to skip that won't be the case. 

as an example, you should pass in a max result count: https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/DefaultArticulateSearcher.cs#L72

be sure to skip with Examine's skip method: 
https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/DefaultArticulateSearcher.cs#L81

you can get the total count by using the property:
https://github.com/Shazwazza/Articulate/blob/master/src/Articulate/DefaultArticulateSearcher.cs#L84

**Comment by mahgo** [comment]
Thanks for that. If I wanted to get the count of a query before paging, and there were hundreds of results, wouldn't they all be returned, with all their data?

**Comment by Shazwazza** [comment]
Nope, the `TotalItemCount` is from Lucene to tell you how many docs it matched, it doesn't load all those docs into memory but if you did a Linq Count() on the results, then yes, you'll load all the results into memory. Lucene loads results lazily.
